name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk security scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }} # Use GitHub Secrets to securely store the Snyk token
        run: |
          npx snyk@1.1285.0 test --all-projects # Specify the version of the snyk package
