name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Snyk Security Scan
        uses: snyk/actions/cli@master
        with:
          args: test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
