name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Navigate to project directory
        run: cd tests

      - name: Snyk Security Scan
        run: snyk test test_area.py
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
